<?xml version="1.0"?>
<package format="3">
  <name>nonsequential_task_bringup</name>
  <version>0.1.0</version>

  <description>
    Launch and configuration files for the namespaced dual-UR system.
  </description>

  <maintainer email="173901397+DamjanDrobac999@users.noreply.github.com">Damjan Drobac</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
