<?xml version="1.0"?>
<package format="3">
  <name>nonsequential_task_meta</name>
  <version>0.1.0</version>

  <description>
    Metapackage for the non-sequential dual-robot thesis project.
  </description>

  <maintainer email="173901397+DamjanDrobac999@users.noreply.github.com">Damjan Drobac</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nonsequential_task_bringup</exec_depend>
  <exec_depend>nonsequential_task_control</exec_depend>
  <exec_depend>nonsequential_task_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
